name: issue key
on: workflow_dispatch
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: Find in commit messages
        uses: atlassian/gajira-find-issue-key@master
        with:
           string: ${{ github.event.ref }}