name: issue key
on: push
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: Find in commit messages
        uses: atlassian/gajira-find-issue-key@master
        with:
           from: commits