name: CI
on: 
  # pull_request: 
  #   branches: [develop, master]
  # push:
  #   branches: [develop, master]
  repository_dispatch:
    branches: [develop]
    types: [test_result]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "14.17"
      - name: cache npm dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - name: publish code coverage
        uses:  actions/upload-artifact@v1
        with:  
          name: code-coverage
          path: coverage
      - name: build project
        if: github.event_name == 'push'
        run: npm run build
      - name: publish build coverage
        if: github.event_name == 'push'
        uses: github.ref == 'refs/heads/master'
        with:  
          name: build
          path: build
      - name: ZIP Assets
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          zip -r build.zip ./build
          zip -r coverage.zip ./coverage
      - name: create release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      - name: Upload Coverage Reports
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
